export enum CommentEvents {
  COMMENT_CREATED = 'COMMENT_CREATED',
  COMMENT_UPDATED = 'COMMENT_UPDATED',
  COMMENT_STATUS_UPDATED = 'COMMENT_STATUS_UPDATED',
  COMMENT_DELETED = 'COMMENT_DELETED',
}
