export enum UserEvents {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_EMAIL_HAS_CHANGED = 'USER_EMAIL_HAS_CHANGED',
}
