export const fieldDescription = {
  vendorCode: 'Артикул',
  manufacturerId: 'id производителя',
  contractorId: 'id поставщика',
  developerUrl: 'Ссылка на сайте застройщика',
  domRfUrl: 'Ссылка на дом.рф',
  executorRate: 'Ставка мастера',
  storeyCount: 'Number of storeys in section',
  roomCountOnStorey: 'Number of rooms on the storey',
  roomCountInRoomGroup: 'Количество помещений',
  livingRoomCount: 'Количество комнат',
  stkCount: 'Количество сантехнических кабин',
  contractSignedDate: 'Дата заключения договора',
  contractPlannedFinishDate: 'Дата завершения договорная',
  constructionSiteReadyDate: 'Дата готовности площадки',
  startDate: 'Дата выхода',
  internalPlannedFinishDate: 'Внутренняя дата завершения',
  documentFolderUrl: 'Ссылка на исходные данные',
  defectionData: 'Данные дефектовки',
  contactorId: 'Id заказчика работ',
  roomGroupArea: 'Площадь квартиры',
};
