export enum DocumentTemplateEvents {
  DOCUMENT_TEMPLATE_CREATED = 'DOCUMENT_TEMPLATE_CREATED',
  DOCUMENT_TEMPLATE_UPDATED = 'DOCUMENT_TEMPLATE_UPDATED',
  DOCUMENT_TEMPLATE_DELETED = 'DOCUMENT_TEMPLATE_DELETED',
}
